/* eslint-disable no-useless-escape */
import { NextResponse } from 'next/server'

type MicroCMSContents = {
    id: string
    createdAt: string
    updatedAt: string
    publishedAt: string
    revisedAt: string
    text: string
}

type MicroCMSResponse = {
    contents: MicroCMSContents[]
    totalCount: number
    offset: number
    limit: number
}

const extractCodeFromText = (text: string): Code => {
    const lines = text.split('\n')
    return { lines }
}

export const GET = () => {
    try {
        const res = `{
            "contents": [
                {
                    "id": "sample1",
                    "createdAt": "2024-06-18T04:35:23.980Z",
                    "updatedAt": "2024-06-18T04:35:23.980Z",
                    "publishedAt": "2024-06-18T04:35:23.980Z",
                    "revisedAt": "2024-06-18T04:35:23.980Z",
                    "text": "import { useRouter } from 'next/router';\\nimport Head from 'next/head';\\n\\nexport default function Post() {\\n  const router = useRouter();\\n  const { id } = router.query;\\n\\n  return (\\n    <div>\\n      <Head>\\n        <title>Post {id}</title>\\n      </Head>\\n      <main>\\n        <h1>Post {id}</h1>\\n        <p>This is the content of post {id}.</p>\\n      </main>\\n    </div>\\n  );\\n}"
                },
                {
                    "id": "sample2",
                    "createdAt": "2024-06-18T04:34:41.186Z",
                    "updatedAt": "2024-06-18T04:34:41.186Z",
                    "publishedAt": "2024-06-18T04:34:41.186Z",
                    "revisedAt": "2024-06-18T04:34:41.186Z",
                    "text": "import Head from 'next/head';\\nimport styles from '../styles/Home.module.css';\\n\\nexport default function Home() {\\n  return (\\n    <div className={styles.container}>\\n      <Head>\\n        <title>Next.js Sample App</title>\\n        <meta name=\\"description\\" content=\\"Generated by create next app\\" />\\n        <link rel=\\"icon\\" href=\\"/favicon.ico\\" />\\n      </Head>\\n\\n      <main className={styles.main}>\\n        <h1 className={styles.title}>\\n          Welcome to <a href=\\"https://nextjs.org\\">Next.js!</a>\\n        </h1>\\n\\n        <p className={styles.description}>\\n          Get started by editing <code className={styles.code}>pages/index.js</code>\\n        </p>\\n      </main>\\n\\n      <footer className={styles.footer}>\\n        <a\\n          href=\\"https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app\\"\\n          target=\\"_blank\\"\\n          rel=\\"noopener noreferrer\\"\\n        >\\n          Powered by{' '}\\n          <span className={styles.logo}>\\n            <img src=\\"/vercel.svg\\" alt=\\"Vercel Logo\\" width={72} height={16} />\\n          </span>\\n        </a>\\n      </footer>\\n    </div>\\n  );\\n}"
                }
            ],
            "totalCount": 2,
            "offset": 0,
            "limit": 10
        }`

        const data = JSON.parse(res) as MicroCMSResponse

        const contents = data.contents

        const content = contents[0]

        const code = extractCodeFromText(content.text)

        return NextResponse.json({ code })
    } catch (error) {
        console.log('CODE_GET', error)
        return new NextResponse('Internal Error', { status: 500 })
    }
}
